services:
  - type: web
    name: sentiment-analyzer-app
    env: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: cd app && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000

